# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanas/editar_videojuego.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 350)
        Dialog.setMinimumSize(QtCore.QSize(562, 350))
        Dialog.setMaximumSize(QtCore.QSize(562, 350))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 130, 501, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.lay_busqueda = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.lay_busqueda.setContentsMargins(0, 0, 0, 0)
        self.lay_busqueda.setObjectName("lay_busqueda")
        self.lbl_id = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_id.setFont(font)
        self.lbl_id.setObjectName("lbl_id")
        self.lay_busqueda.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.lin_id = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lin_id.setObjectName("lin_id")
        self.lay_busqueda.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lin_id)
        self.lbl_titulo = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lay_busqueda.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_titulo)
        self.lin_titulo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lin_titulo.setObjectName("lin_titulo")
        self.lay_busqueda.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lin_titulo)
        self.lbl_plataforma = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_plataforma.setFont(font)
        self.lbl_plataforma.setObjectName("lbl_plataforma")
        self.lay_busqueda.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_plataforma)
        self.lin_plataforma = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lin_plataforma.setObjectName("lin_plataforma")
        self.lay_busqueda.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lin_plataforma)
        self.lbl_genero = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_genero.setFont(font)
        self.lbl_genero.setObjectName("lbl_genero")
        self.lay_busqueda.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_genero)
        self.lin_genero = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lin_genero.setObjectName("lin_genero")
        self.lay_busqueda.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lin_genero)
        self.lbl_precio = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_precio.setFont(font)
        self.lbl_precio.setObjectName("lbl_precio")
        self.lay_busqueda.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_precio)
        self.lin_precio = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lin_precio.setObjectName("lin_precio")
        self.lay_busqueda.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lin_precio)
        self.lbl_introduce = QtWidgets.QLabel(Dialog)
        self.lbl_introduce.setGeometry(QtCore.QRect(30, 30, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(12)
        font.setUnderline(True)
        self.lbl_introduce.setFont(font)
        self.lbl_introduce.setAutoFillBackground(False)
        self.lbl_introduce.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_introduce.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_introduce.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_introduce.setObjectName("lbl_introduce")
        self.btn_buscar_videojuego = QtWidgets.QPushButton(Dialog)
        self.btn_buscar_videojuego.setGeometry(QtCore.QRect(330, 300, 200, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ventanas\\../imagenes/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar_videojuego.setIcon(icon)
        self.btn_buscar_videojuego.setObjectName("btn_buscar_videojuego")
        self.btn_borrar_videojuego = QtWidgets.QPushButton(Dialog)
        self.btn_borrar_videojuego.setEnabled(False)
        self.btn_borrar_videojuego.setGeometry(QtCore.QRect(330, 790, 200, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ventanas\\../imagenes/papelera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_borrar_videojuego.setIcon(icon1)
        self.btn_borrar_videojuego.setObjectName("btn_borrar_videojuego")
        self.lbl_numero_juegos = QtWidgets.QLabel(Dialog)
        self.lbl_numero_juegos.setGeometry(QtCore.QRect(30, 750, 200, 31))
        self.lbl_numero_juegos.setText("")
        self.lbl_numero_juegos.setObjectName("lbl_numero_juegos")
        self.lst_videojuegos_encontrados = QtWidgets.QListWidget(Dialog)
        self.lst_videojuegos_encontrados.setGeometry(QtCore.QRect(30, 350, 501, 401))
        self.lst_videojuegos_encontrados.setObjectName("lst_videojuegos_encontrados")
        self.btn_limpiar_formulario = QtWidgets.QPushButton(Dialog)
        self.btn_limpiar_formulario.setGeometry(QtCore.QRect(30, 300, 200, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ventanas\\../imagenes/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_limpiar_formulario.setIcon(icon2)
        self.btn_limpiar_formulario.setObjectName("btn_limpiar_formulario")
        self.btn_editar_videojuego = QtWidgets.QPushButton(Dialog)
        self.btn_editar_videojuego.setEnabled(False)
        self.btn_editar_videojuego.setGeometry(QtCore.QRect(30, 790, 200, 32))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ventanas\\../imagenes/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editar_videojuego.setIcon(icon3)
        self.btn_editar_videojuego.setObjectName("btn_editar_videojuego")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Borrar / Editar videojuego"))
        self.lbl_id.setText(_translate("Dialog", "Id:"))
        self.lbl_titulo.setText(_translate("Dialog", "Título: "))
        self.lbl_plataforma.setText(_translate("Dialog", "Plataforma: "))
        self.lbl_genero.setText(_translate("Dialog", "Género: "))
        self.lbl_precio.setText(_translate("Dialog", "Precio: "))
        self.lbl_introduce.setText(_translate("Dialog", "Introduce los datos del videojuego\n"
"para la busqueda"))
        self.btn_buscar_videojuego.setText(_translate("Dialog", "Buscar videojuego"))
        self.btn_borrar_videojuego.setText(_translate("Dialog", "Borrar videojuego"))
        self.btn_limpiar_formulario.setText(_translate("Dialog", "Limpiar formulario"))
        self.btn_editar_videojuego.setText(_translate("Dialog", "Modificar videojuego"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
