# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanas/DialogModificarVideojuego.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(432, 625)
        Dialog.setMinimumSize(QtCore.QSize(432, 625))
        Dialog.setMaximumSize(QtCore.QSize(432, 625))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/mando.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lbl_introduzca_datos = QtWidgets.QLabel(Dialog)
        self.lbl_introduzca_datos.setGeometry(QtCore.QRect(10, 10, 411, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_introduzca_datos.setFont(font)
        self.lbl_introduzca_datos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_introduzca_datos.setObjectName("lbl_introduzca_datos")
        self.btn_guardar = QtWidgets.QPushButton(Dialog)
        self.btn_guardar.setEnabled(True)
        self.btn_guardar.setGeometry(QtCore.QRect(220, 540, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_guardar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/diskete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_guardar.setIcon(icon1)
        self.btn_guardar.setAutoDefault(False)
        self.btn_guardar.setObjectName("btn_guardar")
        self.lbl_ayuda = QtWidgets.QLabel(Dialog)
        self.lbl_ayuda.setGeometry(QtCore.QRect(10, 600, 411, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.lbl_ayuda.setFont(font)
        self.lbl_ayuda.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 italic 8pt \"MS Sans Serif\";")
        self.lbl_ayuda.setTextFormat(QtCore.Qt.RichText)
        self.lbl_ayuda.setObjectName("lbl_ayuda")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 110, 411, 422))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.lay_introduzca_datos = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.lay_introduzca_datos.setContentsMargins(0, 0, 0, 0)
        self.lay_introduzca_datos.setHorizontalSpacing(40)
        self.lay_introduzca_datos.setVerticalSpacing(7)
        self.lay_introduzca_datos.setObjectName("lay_introduzca_datos")
        self.lbl_titulo = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lay_introduzca_datos.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_titulo)
        self.le_titulo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_titulo.setObjectName("le_titulo")
        self.lay_introduzca_datos.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_titulo)
        self.lbl_genero = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_genero.setFont(font)
        self.lbl_genero.setObjectName("lbl_genero")
        self.lay_introduzca_datos.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_genero)
        self.le_genero = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_genero.setObjectName("le_genero")
        self.lay_introduzca_datos.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_genero)
        self.lbl_plataforma = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_plataforma.setFont(font)
        self.lbl_plataforma.setObjectName("lbl_plataforma")
        self.lay_introduzca_datos.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_plataforma)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rb_pc = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rb_pc.setChecked(True)
        self.rb_pc.setObjectName("rb_pc")
        self.gridLayout.addWidget(self.rb_pc, 0, 0, 1, 1)
        self.rb_sega = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rb_sega.setObjectName("rb_sega")
        self.gridLayout.addWidget(self.rb_sega, 1, 0, 1, 1)
        self.rb_nintendo = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rb_nintendo.setObjectName("rb_nintendo")
        self.gridLayout.addWidget(self.rb_nintendo, 2, 0, 1, 1)
        self.rb_sony = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rb_sony.setObjectName("rb_sony")
        self.gridLayout.addWidget(self.rb_sony, 0, 1, 1, 1)
        self.rb_microsoft = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rb_microsoft.setObjectName("rb_microsoft")
        self.gridLayout.addWidget(self.rb_microsoft, 1, 1, 1, 1)
        self.lay_introduzca_datos.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.cmb_plataforma = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmb_plataforma.setEnabled(False)
        self.cmb_plataforma.setObjectName("cmb_plataforma")
        self.cmb_plataforma.addItem("")
        self.lay_introduzca_datos.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmb_plataforma)
        self.lbl_nota = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_nota.setOpenExternalLinks(True)
        self.lbl_nota.setObjectName("lbl_nota")
        self.lay_introduzca_datos.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_nota)
        self.dspb_nota = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.dspb_nota.setDecimals(1)
        self.dspb_nota.setMaximum(10.0)
        self.dspb_nota.setObjectName("dspb_nota")
        self.lay_introduzca_datos.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dspb_nota)
        self.lbl_prestado = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_prestado.setObjectName("lbl_prestado")
        self.lay_introduzca_datos.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_prestado)
        self.chb_prestado = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.chb_prestado.setText("")
        self.chb_prestado.setObjectName("chb_prestado")
        self.lay_introduzca_datos.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.chb_prestado)
        self.lbl_anotaciones = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_anotaciones.setObjectName("lbl_anotaciones")
        self.lay_introduzca_datos.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_anotaciones)
        self.lbl_id = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_id.setFont(font)
        self.lbl_id.setTextFormat(QtCore.Qt.RichText)
        self.lbl_id.setObjectName("lbl_id")
        self.lay_introduzca_datos.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.le_id = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_id.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.le_id.setReadOnly(True)
        self.le_id.setObjectName("le_id")
        self.lay_introduzca_datos.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_id)
        self.le_apuntes = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_apuntes.setObjectName("le_apuntes")
        self.lay_introduzca_datos.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.le_apuntes)
        self.btn_imagen = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_imagen.setObjectName("btn_imagen")
        self.lay_introduzca_datos.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.btn_imagen)
        self.lbl_imagen = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_imagen.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lbl_imagen.setFont(font)
        self.lbl_imagen.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_imagen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.lay_introduzca_datos.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lbl_imagen)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Editar Videojuego"))
        self.lbl_introduzca_datos.setText(_translate("Dialog", "Modifique los datos\n"
"del Videojuego"))
        self.btn_guardar.setText(_translate("Dialog", "Guardar"))
        self.lbl_ayuda.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\"><br/></span></p></body></html>"))
        self.lbl_titulo.setText(_translate("Dialog", "Título: "))
        self.lbl_genero.setText(_translate("Dialog", "Género: "))
        self.lbl_plataforma.setText(_translate("Dialog", "Plataforma: "))
        self.rb_pc.setText(_translate("Dialog", "PC"))
        self.rb_sega.setText(_translate("Dialog", "Sega"))
        self.rb_nintendo.setText(_translate("Dialog", "Nintendo"))
        self.rb_sony.setText(_translate("Dialog", "Sony"))
        self.rb_microsoft.setText(_translate("Dialog", "Microsoft"))
        self.cmb_plataforma.setItemText(0, _translate("Dialog", "PC"))
        self.lbl_nota.setText(_translate("Dialog", "Nota (Metacritic): "))
        self.lbl_prestado.setText(_translate("Dialog", "Prestado: "))
        self.lbl_anotaciones.setText(_translate("Dialog", "Anotaciones: "))
        self.lbl_id.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\">Id (no editable): </span></p></body></html>"))
        self.btn_imagen.setText(_translate("Dialog", "Cambiar imagen"))
        self.lbl_imagen.setText(_translate("Dialog", "Sin imagen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
