# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanas/MWBuscarVideojuego.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 651)
        MainWindow.setMinimumSize(QtCore.QSize(432, 651))
        MainWindow.setMaximumSize(QtCore.QSize(432, 651))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/mando.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_introduzca_datos = QtWidgets.QLabel(self.centralwidget)
        self.lbl_introduzca_datos.setGeometry(QtCore.QRect(10, 10, 411, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_introduzca_datos.setFont(font)
        self.lbl_introduzca_datos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_introduzca_datos.setObjectName("lbl_introduzca_datos")
        self.lbl_ayuda = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ayuda.setGeometry(QtCore.QRect(10, 600, 411, 16))
        self.lbl_ayuda.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 italic 8pt \"MS Sans Serif\";")
        self.lbl_ayuda.setObjectName("lbl_ayuda")
        self.btn_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buscar.setGeometry(QtCore.QRect(220, 540, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_buscar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon1)
        self.btn_buscar.setAutoDefault(True)
        self.btn_buscar.setDefault(True)
        self.btn_buscar.setObjectName("btn_buscar")
        self.btn_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_limpiar.setGeometry(QtCore.QRect(10, 540, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_limpiar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/escoba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_limpiar.setIcon(icon2)
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.lbl_resultado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultado.setGeometry(QtCore.QRect(450, 10, 761, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_resultado.setFont(font)
        self.lbl_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resultado.setObjectName("lbl_resultado")
        self.tbl_juegos_encontrados = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_juegos_encontrados.setGeometry(QtCore.QRect(450, 110, 761, 421))
        self.tbl_juegos_encontrados.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_juegos_encontrados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_juegos_encontrados.setObjectName("tbl_juegos_encontrados")
        self.tbl_juegos_encontrados.setColumnCount(8)
        self.tbl_juegos_encontrados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_juegos_encontrados.setHorizontalHeaderItem(7, item)
        self.tbl_juegos_encontrados.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_juegos_encontrados.horizontalHeader().setStretchLastSection(False)
        self.btn_editar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editar.setEnabled(False)
        self.btn_editar.setGeometry(QtCore.QRect(800, 540, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_editar.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/escribir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editar.setIcon(icon3)
        self.btn_editar.setObjectName("btn_editar")
        self.btn_borrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_borrar.setEnabled(False)
        self.btn_borrar.setGeometry(QtCore.QRect(1010, 540, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_borrar.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/papelera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_borrar.setIcon(icon4)
        self.btn_borrar.setObjectName("btn_borrar")
        self.lbl_juegos_encontrados = QtWidgets.QLabel(self.centralwidget)
        self.lbl_juegos_encontrados.setGeometry(QtCore.QRect(450, 600, 761, 16))
        self.lbl_juegos_encontrados.setText("")
        self.lbl_juegos_encontrados.setObjectName("lbl_juegos_encontrados")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 110, 411, 420))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.lay_introduzca_datos = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.lay_introduzca_datos.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lay_introduzca_datos.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.lay_introduzca_datos.setContentsMargins(0, 0, 0, 0)
        self.lay_introduzca_datos.setHorizontalSpacing(66)
        self.lay_introduzca_datos.setVerticalSpacing(21)
        self.lay_introduzca_datos.setObjectName("lay_introduzca_datos")
        self.lbl_id = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_id.setFont(font)
        self.lbl_id.setObjectName("lbl_id")
        self.lay_introduzca_datos.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_id)
        self.le_id = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_id.setReadOnly(False)
        self.le_id.setObjectName("le_id")
        self.lay_introduzca_datos.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_id)
        self.lbl_titulo = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lay_introduzca_datos.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_titulo)
        self.le_titulo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_titulo.setObjectName("le_titulo")
        self.lay_introduzca_datos.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_titulo)
        self.lbl_genero = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_genero.setFont(font)
        self.lbl_genero.setObjectName("lbl_genero")
        self.lay_introduzca_datos.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_genero)
        self.le_genero = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_genero.setObjectName("le_genero")
        self.lay_introduzca_datos.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_genero)
        self.lbl_plataforma = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_plataforma.setFont(font)
        self.lbl_plataforma.setObjectName("lbl_plataforma")
        self.lay_introduzca_datos.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_plataforma)
        self.cmb_plataforma = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmb_plataforma.setEnabled(False)
        self.cmb_plataforma.setObjectName("cmb_plataforma")
        self.cmb_plataforma.addItem("")
        self.lay_introduzca_datos.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmb_plataforma)
        self.lbl_prestado = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_prestado.setObjectName("lbl_prestado")
        self.lay_introduzca_datos.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_prestado)
        self.lbl_anotaciones = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_anotaciones.setObjectName("lbl_anotaciones")
        self.lay_introduzca_datos.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_anotaciones)
        self.le_apuntes = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_apuntes.sizePolicy().hasHeightForWidth())
        self.le_apuntes.setSizePolicy(sizePolicy)
        self.le_apuntes.setObjectName("le_apuntes")
        self.lay_introduzca_datos.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_apuntes)
        self.gb_plataformas = QtWidgets.QGroupBox(self.formLayoutWidget)
        self.gb_plataformas.setEnabled(True)
        self.gb_plataformas.setCheckable(True)
        self.gb_plataformas.setObjectName("gb_plataformas")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_plataformas)
        self.gridLayout.setObjectName("gridLayout")
        self.rb_nintendo = QtWidgets.QRadioButton(self.gb_plataformas)
        self.rb_nintendo.setEnabled(False)
        self.rb_nintendo.setObjectName("rb_nintendo")
        self.gridLayout.addWidget(self.rb_nintendo, 2, 0, 1, 1)
        self.rb_sega = QtWidgets.QRadioButton(self.gb_plataformas)
        self.rb_sega.setEnabled(False)
        self.rb_sega.setObjectName("rb_sega")
        self.gridLayout.addWidget(self.rb_sega, 1, 0, 1, 1)
        self.rb_microsoft = QtWidgets.QRadioButton(self.gb_plataformas)
        self.rb_microsoft.setEnabled(False)
        self.rb_microsoft.setObjectName("rb_microsoft")
        self.gridLayout.addWidget(self.rb_microsoft, 1, 1, 1, 1)
        self.rb_pc = QtWidgets.QRadioButton(self.gb_plataformas)
        self.rb_pc.setEnabled(False)
        self.rb_pc.setChecked(True)
        self.rb_pc.setObjectName("rb_pc")
        self.gridLayout.addWidget(self.rb_pc, 0, 0, 1, 1)
        self.rb_sony = QtWidgets.QRadioButton(self.gb_plataformas)
        self.rb_sony.setEnabled(False)
        self.rb_sony.setObjectName("rb_sony")
        self.gridLayout.addWidget(self.rb_sony, 0, 1, 1, 1)
        self.lay_introduzca_datos.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gb_plataformas)
        self.gb_prestado = QtWidgets.QGroupBox(self.formLayoutWidget)
        self.gb_prestado.setCheckable(True)
        self.gb_prestado.setObjectName("gb_prestado")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_prestado)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rb_prestado_si = QtWidgets.QRadioButton(self.gb_prestado)
        self.rb_prestado_si.setEnabled(False)
        self.rb_prestado_si.setChecked(False)
        self.rb_prestado_si.setObjectName("rb_prestado_si")
        self.gridLayout_2.addWidget(self.rb_prestado_si, 0, 0, 1, 1)
        self.rb_prestado_no = QtWidgets.QRadioButton(self.gb_prestado)
        self.rb_prestado_no.setEnabled(False)
        self.rb_prestado_no.setChecked(True)
        self.rb_prestado_no.setObjectName("rb_prestado_no")
        self.gridLayout_2.addWidget(self.rb_prestado_no, 0, 1, 1, 1)
        self.lay_introduzca_datos.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gb_prestado)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buscar Videojuego"))
        self.lbl_introduzca_datos.setText(_translate("MainWindow", "Introduzca los datos\n"
"del Videojuego a buscar"))
        self.lbl_ayuda.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_buscar.setText(_translate("MainWindow", "Buscar"))
        self.btn_limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.lbl_resultado.setText(_translate("MainWindow", "Resultado"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Título"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Plataforma"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Género"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Nota"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Prestado"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Apuntes"))
        item = self.tbl_juegos_encontrados.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Imagen"))
        self.btn_editar.setText(_translate("MainWindow", "Editar"))
        self.btn_borrar.setText(_translate("MainWindow", "Borrar"))
        self.lbl_id.setText(_translate("MainWindow", "Id: "))
        self.lbl_titulo.setText(_translate("MainWindow", "Título: "))
        self.lbl_genero.setText(_translate("MainWindow", "Género: "))
        self.lbl_plataforma.setText(_translate("MainWindow", "Plataforma: "))
        self.cmb_plataforma.setItemText(0, _translate("MainWindow", "PC"))
        self.lbl_prestado.setText(_translate("MainWindow", "Prestado: "))
        self.lbl_anotaciones.setText(_translate("MainWindow", "Anotaciones: "))
        self.gb_plataformas.setTitle(_translate("MainWindow", "Todas"))
        self.rb_nintendo.setText(_translate("MainWindow", "Nintendo"))
        self.rb_sega.setText(_translate("MainWindow", "Sega"))
        self.rb_microsoft.setText(_translate("MainWindow", "Microsoft"))
        self.rb_pc.setText(_translate("MainWindow", "PC"))
        self.rb_sony.setText(_translate("MainWindow", "Sony"))
        self.gb_prestado.setTitle(_translate("MainWindow", "Todos"))
        self.rb_prestado_si.setText(_translate("MainWindow", "Si"))
        self.rb_prestado_no.setText(_translate("MainWindow", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
