# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanas/MWListadoTableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 640)
        MainWindow.setMinimumSize(QtCore.QSize(800, 640))
        MainWindow.setMaximumSize(QtCore.QSize(800, 640))
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ventanas\\imagenes_ventanas/mando.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_listado_videojuegos = QtWidgets.QLabel(self.centralwidget)
        self.lbl_listado_videojuegos.setGeometry(QtCore.QRect(10, 10, 780, 90))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_listado_videojuegos.setFont(font)
        self.lbl_listado_videojuegos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_listado_videojuegos.setObjectName("lbl_listado_videojuegos")
        self.lbl_juegos_listados = QtWidgets.QLabel(self.centralwidget)
        self.lbl_juegos_listados.setGeometry(QtCore.QRect(10, 590, 781, 16))
        self.lbl_juegos_listados.setText("")
        self.lbl_juegos_listados.setObjectName("lbl_juegos_listados")
        self.tbl_listado_videojuegos = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_listado_videojuegos.setGeometry(QtCore.QRect(10, 110, 780, 471))
        self.tbl_listado_videojuegos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_listado_videojuegos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_listado_videojuegos.setObjectName("tbl_listado_videojuegos")
        self.tbl_listado_videojuegos.setColumnCount(8)
        self.tbl_listado_videojuegos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(True)
        item.setFont(font)
        self.tbl_listado_videojuegos.setHorizontalHeaderItem(7, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.subm_anadir_videjuego = QtWidgets.QAction(MainWindow)
        self.subm_anadir_videjuego.setObjectName("subm_anadir_videjuego")
        self.subm_editar_videojuego = QtWidgets.QAction(MainWindow)
        self.subm_editar_videojuego.setObjectName("subm_editar_videojuego")
        self.subm_borrar_videojuego = QtWidgets.QAction(MainWindow)
        self.subm_borrar_videojuego.setObjectName("subm_borrar_videojuego")
        self.subm_listado_normal = QtWidgets.QAction(MainWindow)
        self.subm_listado_normal.setObjectName("subm_listado_normal")
        self.subm_listado_list_widget = QtWidgets.QAction(MainWindow)
        self.subm_listado_list_widget.setObjectName("subm_listado_list_widget")
        self.subm_listado_table_widget = QtWidgets.QAction(MainWindow)
        self.subm_listado_table_widget.setObjectName("subm_listado_table_widget")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Listado Table Widget"))
        self.lbl_listado_videojuegos.setText(_translate("MainWindow", "Listado de Videojuegos"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Título"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Plataforma"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Género"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Nota"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Prestado"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Apuntes"))
        item = self.tbl_listado_videojuegos.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Imagen"))
        self.subm_anadir_videjuego.setText(_translate("MainWindow", "Añadir Videojuego"))
        self.subm_editar_videojuego.setText(_translate("MainWindow", "Editar Videojuego"))
        self.subm_borrar_videojuego.setText(_translate("MainWindow", "Borrar Videojuego"))
        self.subm_listado_normal.setText(_translate("MainWindow", "Listado Normal"))
        self.subm_listado_list_widget.setText(_translate("MainWindow", "Listado (List Widget)"))
        self.subm_listado_table_widget.setText(_translate("MainWindow", "Listado (Table Widget)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
